language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-snugug' ]; then cd .. && eval "mv $currentfolder generator-snugug" && cd generator-snugug; fi

